version: '3'

services:
  redis-db:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./redis-data:/data
    networks:
      - mynet

  service:
    container_name: file-tracker
    build: service
    restart: always
    volumes:
      - ./service:/usr/src/app
      - ./files:/usr/src/files
    ports:
      - "3000:3000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
